### ISSUE TITLE
Publish summary pave condition

### ISSUE THREAD

**Issue by kviani** [VTrans/vtp3-pavement#10]
[Assets_Admin].[VTP3_PaveCond] is ready to be copied to web and published as service

**Comment by mlofgren** [comment]
Done
http://vtransmap01.aot.state.vt.us/arcgis/rest/services/vtp3/VTransparencyFeatureOnlyData/FeatureServer

**Comment by mlofgren** [comment]
do stuff with these

**Comment by srsjojo** [comment]
Where did the service go?  :confused:

**Comment by srsjojo** [comment]
Removed - won't work with ODP charting
