### ISSUE TITLE
Redundancies in legend, update popup

### ISSUE THREAD

**Issue by srsjojo** [VTrans/vtp3-pavement#15]
- [x] "pavement condition 13" vs "pavement condition 13 one mile"
- [x] "Projects" vs "Planned paving project locations"
- [x] custom configure the popup to say the chart is on a 1-100 scale
- [ ] explain why the chart disappears at the .1 mi zoom level

**Comment by srsjojo** [comment]
maybe "Condition is on a scale from 0 to 100 (best = 100)"

**Comment by rkiniry** [comment]
No explanation for chart disappearance at tenth mile segmentation.

**Comment by srsjojo** [comment]
:+1:
