### ISSUE TITLE
Pavement data updates

### ISSUE THREAD

**Issue by srsjojo** [VTrans/vtp3-pavement#3]
Please update your data source:
- [x] Rename the title of the pavement data to something more human readable than `PavementCondition2013VTP3`  
- [x] Add a full-metadata description
- [x] Describe the primary dataset attributes
- [x] Add a thumbnail image

**Comment by rkiniry** [comment]
renamed, desciption added, don't know how to edit attributes, need help with thumbnail.

**Comment by rkiniry** [comment]
Thumbnail done, waiting for esri for attributes

**Comment by rkiniry** [comment]
metadata done as part of republish
