### ISSUE TITLE
Add route, town to pop up box

### ISSUE THREAD

**Issue by srsjojo** [VTrans/vtp3-pavement#4]
@snailorvt was too lazy to fill out this issue himself :-1: 
![2014-10-23 10 14 46](https://cloud.githubusercontent.com/assets/7338435/4755405/438a1256-5ac5-11e4-9ba6-d8b79de5b262.jpg)

**Comment by snailorvt** [comment]
Really impatient, not all of us get to sit at a computer all day!

**Comment by rkiniry** [comment]
Road added ete lr value in pop up, status remaining "in progress". route name and town being added to data source. working on table cleanup before service republish

**Comment by rkiniry** [comment]
done as part of republish
